spring.application.name=square-games-api

server.port=8082

# Api user address
users.service.url=http://localhost:8083/api/v1/users

# Configuration profil DB par défaut de test H2
# spring.profiles.active=h2
spring.profiles.active=mysql

# Configuration du jeu
game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.taquin.default-player-count=1
game.taquin.default-board-size=3

game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

# Internationalization
spring.messages.basename=messages
spring.messages.encoding=UTF-8

