@BASE_URL_CATALOG = http://localhost:8082/api/v1/catalog
@BASE_URL_GAMES = http://localhost:8082/api/v1/games


### Catalogue en français
GET {{BASE_URL_CATALOG}}
Accept-Language: fr

### Catalogue en anglais
GET {{BASE_URL_CATALOG}}
Accept-Language: en

### Créer une partie avec les valeurs par défaut
POST {{BASE_URL_GAMES}}
Content-Type: application/json

{
  "gameType": "tictactoe"
}

### Créer une partie avec des valeurs personnalisées
POST {{BASE_URL_GAMES}}
Content-Type: application/json

{
  "gameType": "tictactoe",
  "playerCount": 2,
  "boardSize": 3
}

### Récupérer l'état d'une partie (remplace l'uuid)
GET {{BASE_URL_GAMES}}/bcfefa2a-085d-4966-927b-e3d4f204b814

### Lister les coups possibles
GET {{BASE_URL_GAMES}}/bcfefa2a-085d-4966-927b-e3d4f204b814/moves

### Jouer un coup
POST {{BASE_URL_GAMES}}/bcfefa2a-085d-4966-927b-e3d4f204b814/moves
Content-Type: application/json

{
  "tokenName": "X",
  "posX": 1,
  "posY": 0
}